package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"errors"
	"storeapi/internal/models"
)

// Type is the resolver for the type field. Exposed as a plain string; see AddressType in internal/models/address.go.
func (r *addressResolver) Type(ctx context.Context, obj *models.Address) (string, error) {
	return string(obj.Type), nil
}

// CreateAddress is the resolver for the createAddress field.
func (r *mutationResolver) CreateAddress(ctx context.Context, recipient string, lineOne string, lineTwo *string, city string, state string, zipCode string, typeArg string) (*models.Address, error) {
	user, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	address := &models.Address{
		Recipient: recipient,
		LineOne:   lineOne,
		City:      city,
		State:     state,
		ZipCode:   zipCode,
		Type:      models.AddressType(typeArg),
		UserID:    user.ID,
	}
	if lineTwo != nil {
		address.LineTwo = *lineTwo
	}

	if err := r.DB.Create(address).Error; err != nil {
		return nil, err
	}
	return address, nil
}

// UpdateAddress is the resolver for the updateAddress field.
func (r *mutationResolver) UpdateAddress(ctx context.Context, id string, recipient *string, lineOne *string, lineTwo *string, city *string, state *string, zipCode *string, typeArg *string) (*models.Address, error) {
	user, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	var address models.Address
	if err := r.DB.Where("id = ? AND user_id = ?", id, user.ID).First(&address).Error; err != nil {
		return nil, errors.New("Invalid id")
	}

	if recipient != nil {
		address.Recipient = *recipient
	}
	if lineOne != nil {
		address.LineOne = *lineOne
	}
	if lineTwo != nil {
		address.LineTwo = *lineTwo
	}
	if city != nil {
		address.City = *city
	}
	if state != nil {
		address.State = *state
	}
	if zipCode != nil {
		address.ZipCode = *zipCode
	}
	if typeArg != nil {
		address.Type = models.AddressType(*typeArg)
	}

	if err := r.DB.Save(&address).Error; err != nil {
		return nil, err
	}
	return &address, nil
}

// DeleteAddress is the resolver for the deleteAddress field.
func (r *mutationResolver) DeleteAddress(ctx context.Context, id string) (bool, error) {
	user, err := requireUser(ctx)
	if err != nil {
		return false, err
	}

	result := r.DB.Where("id = ? AND user_id = ?", id, user.ID).Delete(&models.Address{})
	if result.Error != nil {
		return false, result.Error
	}
	return result.RowsAffected > 0, nil
}

// Addresses is the resolver for the addresses field.
func (r *queryResolver) Addresses(ctx context.Context) ([]*models.Address, error) {
	user, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	var addresses []*models.Address
	if err := r.DB.Where("user_id = ?", user.ID).Find(&addresses).Error; err != nil {
		return nil, err
	}
	return addresses, nil
}

// Address is the resolver for the address field.
func (r *queryResolver) Address(ctx context.Context, id string) (*models.Address, error) {
	user, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	var address models.Address
	if err := r.DB.Where("id = ? AND user_id = ?", id, user.ID).First(&address).Error; err != nil {
		return nil, errors.New("Invalid id")
	}
	return &address, nil
}

// Address returns AddressResolver implementation.
func (r *Resolver) Address() AddressResolver { return &addressResolver{r} }

type addressResolver struct{ *Resolver }
