package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"errors"
	"storeapi/internal/models"
)

// AddToCart is the resolver for the addToCart field.
func (r *mutationResolver) AddToCart(ctx context.Context, productID string) ([]*models.UserProduct, error) {
	user, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	var cartItem models.UserProduct
	err = r.DB.Where("user_id = ? AND product_id = ?", user.ID, productID).
		Preload("Product").First(&cartItem).Error
	if err == nil {
		if cartItem.Product.Quantity <= cartItem.Count && !cartItem.Product.IsMadeToOrder {
			return nil, errors.New("You cannot add more than what is available unless it can be made to order.")
		}
		cartItem.Count++
		if err := r.DB.Save(&cartItem).Error; err != nil {
			return nil, err
		}
	} else {
		if err := r.DB.Create(&models.UserProduct{UserID: user.ID, ProductID: productID}).Error; err != nil {
			return nil, err
		}
	}

	var cart []*models.UserProduct
	if err := r.DB.Where("user_id = ?", user.ID).Find(&cart).Error; err != nil {
		return nil, err
	}
	return cart, nil
}

// RemoveFromCart is the resolver for the removeFromCart field.
func (r *mutationResolver) RemoveFromCart(ctx context.Context, productID string) ([]*models.UserProduct, error) {
	user, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	var cartItem models.UserProduct
	err = r.DB.Where("user_id = ? AND product_id = ?", user.ID, productID).First(&cartItem).Error
	if err == nil {
		if cartItem.Count == 1 {
			if err := r.DB.Delete(&cartItem).Error; err != nil {
				return nil, err
			}
		} else {
			cartItem.Count--
			if err := r.DB.Save(&cartItem).Error; err != nil {
				return nil, err
			}
		}
	}

	var cart []*models.UserProduct
	if err := r.DB.Where("user_id = ?", user.ID).Find(&cart).Error; err != nil {
		return nil, err
	}
	return cart, nil
}

// Count is the resolver for the count field. Float on the wire; the Go model keeps a plain int.
func (r *userProductResolver) Count(ctx context.Context, obj *models.UserProduct) (float64, error) {
	return float64(obj.Count), nil
}

// Product is the resolver for the product field.
func (r *userProductResolver) Product(ctx context.Context, obj *models.UserProduct) (*models.Product, error) {
	product, err := loaders(ctx).Product.Load(ctx, obj.ProductID)
	if err != nil {
		return nil, err
	}
	if product == nil {
		return nil, errors.New("User product needs a product associated.")
	}
	return product, nil
}

// UserProduct returns UserProductResolver implementation.
func (r *Resolver) UserProduct() UserProductResolver { return &userProductResolver{r} }

type userProductResolver struct{ *Resolver }
