package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"storeapi/internal/models"
)

// Products is the resolver for the products field.
func (r *categoryResolver) Products(ctx context.Context, obj *models.Category) ([]*models.Product, error) {
	var productCategories []models.ProductCategory
	err := r.DB.Where("category_id = ?", obj.ID).Preload("Product").Find(&productCategories).Error
	if err != nil {
		return nil, err
	}

	products := make([]*models.Product, 0, len(productCategories))
	for _, pc := range productCategories {
		if pc.Product != nil {
			products = append(products, pc.Product)
		}
	}
	return products, nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, name string) (*models.Category, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return nil, err
	}

	category := &models.Category{Name: name}
	if err := r.DB.Create(category).Error; err != nil {
		return nil, err
	}
	return category, nil
}

// AttachCategory is the resolver for the attachCategory field.
func (r *mutationResolver) AttachCategory(ctx context.Context, categoryID string, productID *string, contentID *string) (bool, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return false, err
	}

	if productID != nil {
		pc := &models.ProductCategory{ProductID: *productID, CategoryID: categoryID}
		if err := r.DB.Create(pc).Error; err != nil {
			return false, err
		}
		return true, nil
	}

	if contentID != nil {
		cc := &models.ContentCategory{ContentID: *contentID, CategoryID: categoryID}
		if err := r.DB.Create(cc).Error; err != nil {
			return false, err
		}
		return true, nil
	}

	return false, nil
}

// DetachCategory is the resolver for the detachCategory field.
func (r *mutationResolver) DetachCategory(ctx context.Context, categoryID string, productID *string, contentID *string) (bool, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return false, err
	}

	if productID != nil {
		result := r.DB.Where("product_id = ? AND category_id = ?", *productID, categoryID).
			Delete(&models.ProductCategory{})
		if result.Error != nil {
			return false, result.Error
		}
		return result.RowsAffected > 0, nil
	}

	if contentID != nil {
		// Matches the Node resolver's apparent bug: it filters by
		// `{ contentId: categoryId }`, using the outer categoryId argument
		// as the contentId filter and never referencing contentId at all.
		result := r.DB.Where("content_id = ?", categoryID).Delete(&models.ContentCategory{})
		if result.Error != nil {
			return false, result.Error
		}
		return result.RowsAffected > 0, nil
	}

	return false, nil
}

// ClearFeatures is the resolver for the clearFeatures field.
func (r *mutationResolver) ClearFeatures(ctx context.Context) (bool, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return false, err
	}

	result := r.DB.Where(
		"category_id IN (SELECT id FROM categories WHERE name = ?)", "Feature",
	).Delete(&models.ProductCategory{})
	if result.Error != nil {
		return false, result.Error
	}
	return result.RowsAffected > 0, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context, search *string, list *bool) ([]*models.Category, error) {
	query := r.DB.Model(&models.Category{}).Order("categories.name ASC")
	if search != nil && *search != "" {
		query = query.Where("categories.name ILIKE ?", "%"+*search+"%")
	}

	// Matches CategoryResolver.categories' `list` branch: an INNER JOIN
	// through product_categories to active products, one query — not a
	// COUNT per category (that was a real N+1 regression from the Node
	// version's single-query `include`, caught by benchmarking this
	// endpoint against the Node server side by side).
	if list != nil && *list {
		query = query.Distinct().
			Joins("JOIN product_categories ON product_categories.category_id = categories.id").
			Joins("JOIN products ON products.id = product_categories.product_id AND products.is_active = true")
	}

	var categories []*models.Category
	if err := query.Find(&categories).Error; err != nil {
		return nil, err
	}
	return categories, nil
}

// Category returns CategoryResolver implementation.
func (r *Resolver) Category() CategoryResolver { return &categoryResolver{r} }

type categoryResolver struct{ *Resolver }
