package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"errors"
	"storeapi/internal/models"
)

// Categories is the resolver for the categories field.
func (r *contentResolver) Categories(ctx context.Context, obj *models.Content) ([]*models.Category, error) {
	var categories []*models.Category
	err := r.DB.Table("categories").
		Joins("JOIN content_categories ON content_categories.category_id = categories.id").
		Where("content_categories.content_id = ?", obj.ID).
		Find(&categories).Error
	if err != nil {
		return nil, err
	}
	return categories, nil
}

// CreateContent is the resolver for the createContent field.
func (r *mutationResolver) CreateContent(ctx context.Context, detail string, title *string) (*models.Content, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return nil, err
	}

	content := &models.Content{Detail: detail}
	if title != nil {
		content.Title = *title
	}
	if err := r.DB.Create(content).Error; err != nil {
		return nil, err
	}
	return content, nil
}

// UpdateContent is the resolver for the updateContent field.
func (r *mutationResolver) UpdateContent(ctx context.Context, id string, title *string, detail *string) (*models.Content, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return nil, err
	}

	var content models.Content
	if err := r.DB.Where("id = ?", id).First(&content).Error; err != nil {
		return nil, errors.New("Invalid id")
	}

	if title != nil {
		content.Title = *title
	}
	if detail != nil {
		content.Detail = *detail
	}

	if err := r.DB.Save(&content).Error; err != nil {
		return nil, err
	}
	return &content, nil
}

// DeleteContent is the resolver for the deleteContent field.
func (r *mutationResolver) DeleteContent(ctx context.Context, id string) (bool, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return false, err
	}

	result := r.DB.Where("id = ?", id).Delete(&models.Content{})
	if result.Error != nil {
		return false, result.Error
	}
	return result.RowsAffected > 0, nil
}

// Contents is the resolver for the contents field.
func (r *queryResolver) Contents(ctx context.Context, search *string) ([]*models.Content, error) {
	query := r.DB.Model(&models.Content{})

	if search != nil && *search != "" {
		query = query.Where(
			"id IN (SELECT content_categories.content_id FROM content_categories "+
				"JOIN categories ON categories.id = content_categories.category_id "+
				"WHERE categories.name ILIKE ?)",
			"%"+*search+"%",
		)
	}

	var contents []*models.Content
	if err := query.Find(&contents).Error; err != nil {
		return nil, err
	}
	return contents, nil
}

// Content is the resolver for the content field.
func (r *queryResolver) Content(ctx context.Context, id string) (*models.Content, error) {
	var content models.Content
	if err := r.DB.Where("id = ?", id).First(&content).Error; err != nil {
		return nil, errors.New("Invalid id")
	}
	return &content, nil
}

// Content returns ContentResolver implementation.
func (r *Resolver) Content() ContentResolver { return &contentResolver{r} }

type contentResolver struct{ *Resolver }
