package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"encoding/json"
	"net/url"
	"storeapi/internal/logger"
	"storeapi/internal/models"
	"strings"

	"gorm.io/datatypes"
)

// Ping is the resolver for the ping field. Matches GeneralResolver.ping in server/src/resolvers/general.ts: logs an Analytic row (skipped for known bots), always returns "pong".
func (r *mutationResolver) Ping(ctx context.Context, path string) (string, error) {
	c := fiberCtx(ctx)

	var userAgent, origin, xForwardedFor, remoteAddr string
	if c != nil {
		userAgent = c.Get("User-Agent")
		origin = c.Get("Origin")
		xForwardedFor = c.Get("X-Forwarded-For")
		remoteAddr = c.IP()
	}

	if strings.Contains(userAgent, "(compatible; Googlebot/2.1; +http://www.google.com/bot.html)") ||
		strings.Contains(userAgent, "Vercelbot/0.1 (+https://vercel.com)") {
		return "pong", nil
	}

	parsed, err := url.Parse(origin + path)
	if err != nil {
		// Same as the Node resolver's implicit behavior: a bad path just
		// means a less useful analytics row, not a failed ping.
		return "pong", nil
	}
	query := parsed.Query()

	ip := xForwardedFor
	if ip == "" {
		ip = remoteAddr
	}

	queryJSON, err := json.Marshal(flattenQuery(query))
	if err != nil {
		logger.Error("Error encoding ping query", "error", err)
		return "pong", nil
	}

	analytic := &models.Analytic{
		IP:        ip,
		UserAgent: userAgent,
		Page:      parsed.Path,
		Modal:     query.Get("modal"),
		ModalID:   query.Get("id"),
		Token:     tokenFromContext(ctx),
		Query:     datatypes.JSON(queryJSON),
	}
	if user := currentUser(ctx); user != nil {
		analytic.UserID = user.ID
	}

	// Matches the Node resolver: analytics failures are logged, not surfaced.
	if err := r.DB.Create(analytic).Error; err != nil {
		logger.Error("Error creating analytic", "error", err)
	}

	return "pong", nil
}
