package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"storeapi/internal/models"

	"github.com/cloudinary/cloudinary-go/v2/api/uploader"
)

// DeleteImage is the resolver for the deleteImage field.
func (r *mutationResolver) DeleteImage(ctx context.Context, id string) (bool, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return false, err
	}

	cld, err := newCloudinaryClient()
	if err != nil {
		return false, err
	}
	if _, err := cld.Upload.Destroy(ctx, uploader.DestroyParams{PublicID: id}); err != nil {
		return false, err
	}
	return true, nil
}

// AttachImage is the resolver for the attachImage field.
func (r *mutationResolver) AttachImage(ctx context.Context, productID string, url string, primary bool, title *string, description *string) (*models.ProductImage, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return nil, err
	}

	var record models.ProductImage
	if err := r.DB.Where("product_id = ? AND url = ?", productID, url).First(&record).Error; err != nil {
		record = models.ProductImage{ProductID: productID, URL: url}
	}

	record.Primary = primary
	if title != nil {
		record.Title = *title
	}
	if description != nil {
		record.Description = *description
	}

	// GORM's Save creates when ID is unset and updates otherwise, matching
	// the Node resolver's `record.save()` on either a freshly-built or an
	// already-persisted instance.
	if err := r.DB.Save(&record).Error; err != nil {
		return nil, err
	}
	return &record, nil
}

// DetachImage is the resolver for the detachImage field.
func (r *mutationResolver) DetachImage(ctx context.Context, id string) (bool, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return false, err
	}

	result := r.DB.Where("id = ?", id).Delete(&models.ProductImage{})
	if result.Error != nil {
		return false, result.Error
	}
	return result.RowsAffected > 0, nil
}

// ImageUrls is the resolver for the imageUrls field.
func (r *queryResolver) ImageUrls(ctx context.Context) ([]string, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return nil, err
	}

	assets, err := listCloudinaryAssets(ctx)
	if err != nil {
		return nil, err
	}

	urls := make([]string, len(assets))
	for i, asset := range assets {
		urls[i] = asset.URL
	}

	attached, err := attachedImageURLs(r.DB, urls)
	if err != nil {
		return nil, err
	}

	out := make([]string, 0, len(urls))
	for _, u := range urls {
		if !attached[u] {
			out = append(out, u)
		}
	}
	return out, nil
}

// Images is the resolver for the images field.
func (r *queryResolver) Images(ctx context.Context) ([]*Image, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return nil, err
	}

	assets, err := listCloudinaryAssets(ctx)
	if err != nil {
		return nil, err
	}

	urls := make([]string, len(assets))
	for i, asset := range assets {
		urls[i] = asset.URL
	}

	attached, err := attachedImageURLs(r.DB, urls)
	if err != nil {
		return nil, err
	}

	images := make([]*Image, 0, len(assets))
	for _, asset := range assets {
		if attached[asset.URL] {
			continue
		}
		publicID := asset.PublicID
		images = append(images, &Image{URL: asset.URL, ID: &publicID})
	}
	return images, nil
}

// ImageUploadSignature is the resolver for the imageUploadSignature field.
func (r *queryResolver) ImageUploadSignature(ctx context.Context) (*ImageUploadSignature, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	return newImageUploadSignature()
}
