package graph

// This file is NOT regenerated by gqlgen — shared Cloudinary helpers for
// image.resolvers.go, matching the v2.config()/v2.api/v2.utils calls in
// server/src/resolvers/image.ts.

import (
	"context"
	"net/url"
	"os"
	"strconv"
	"time"

	"gorm.io/gorm"

	cloudinary "github.com/cloudinary/cloudinary-go/v2"
	"github.com/cloudinary/cloudinary-go/v2/api"
	"github.com/cloudinary/cloudinary-go/v2/api/admin"

	"storeapi/internal/models"
)

func newCloudinaryClient() (*cloudinary.Cloudinary, error) {
	return cloudinary.NewFromParams(
		os.Getenv("CLOUDINARY_CLOUD_NAME"),
		os.Getenv("CLOUDINARY_API_KEY"),
		os.Getenv("CLOUDINARY_API_SECRET"),
	)
}

// listCloudinaryAssets matches the shared `v2.api.resources({ prefix:
// "store", resource_type: "image", type: "upload", max_results: 500 })`
// call duplicated across imageUrls/images in the Node resolver.
func listCloudinaryAssets(ctx context.Context) ([]api.BriefAssetResult, error) {
	cld, err := newCloudinaryClient()
	if err != nil {
		return nil, err
	}

	result, err := cld.Admin.Assets(ctx, admin.AssetsParams{
		AssetType:    api.Image,
		DeliveryType: "upload",
		Prefix:       "store",
		MaxResults:   500,
	})
	if err != nil {
		return nil, err
	}
	return result.Assets, nil
}

// attachedImageURLs matches the `ProductImage.findAll({where:{url: urls}})`
// filter used to exclude already-attached Cloudinary assets.
func attachedImageURLs(db *gorm.DB, urls []string) (map[string]bool, error) {
	var existing []string
	if len(urls) > 0 {
		if err := db.Model(&models.ProductImage{}).Where("url IN ?", urls).Pluck("url", &existing).Error; err != nil {
			return nil, err
		}
	}

	attached := make(map[string]bool, len(existing))
	for _, u := range existing {
		attached[u] = true
	}
	return attached, nil
}

// newImageUploadSignature matches ImageResolver.imageUploadSignature.
func newImageUploadSignature() (*ImageUploadSignature, error) {
	timestamp := int(time.Now().Unix())

	params := url.Values{
		"timestamp": {strconv.Itoa(timestamp)},
		"folder":    {"store"},
	}
	signature, err := api.SignParameters(params, os.Getenv("CLOUDINARY_API_SECRET"))
	if err != nil {
		return nil, err
	}

	return &ImageUploadSignature{
		Timestamp: timestamp,
		Signature: signature,
		Cloudname: os.Getenv("CLOUDINARY_CLOUD_NAME"),
		Apikey:    os.Getenv("CLOUDINARY_API_KEY"),
	}, nil
}
