// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"storeapi/internal/models"
)

type Image struct {
	URL string  `json:"url"`
	ID  *string `json:"id,omitempty"`
}

type ImageUploadSignature struct {
	Timestamp int    `json:"timestamp"`
	Signature string `json:"signature"`
	Cloudname string `json:"cloudname"`
	Apikey    string `json:"apikey"`
}

type Mutation struct {
}

type OrderPage struct {
	HasMore  bool            `json:"hasMore"`
	NextPage *float64        `json:"nextPage,omitempty"`
	Edges    []*models.Order `json:"edges"`
}

type ProductPage struct {
	HasMore  bool              `json:"hasMore"`
	NextPage *float64          `json:"nextPage,omitempty"`
	Edges    []*models.Product `json:"edges"`
}

type Query struct {
}
