package graph

// This file is NOT regenerated by gqlgen (no schema field matches these
// signatures) — shared helpers for order.resolvers.go live here instead of
// getting shuffled to the bottom of the generated file on every `gqlgen
// generate`.

import (
	"context"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/stripe/stripe-go/v84"

	"storeapi/internal/models"
)

// checkPaymentSucceeded backs both the paymentSucceeded query and
// placeOrder. Note: the Node resolver's `existingOrder` lookup is a no-op
// (`if (existingOrder) false;` — missing `return`), so it has no effect and
// isn't replicated here.
func (r *Resolver) checkPaymentSucceeded(ctx context.Context, clientSecret string) (bool, error) {
	paymentIntentID := strings.Split(clientSecret, "_secret")[0]

	sc := stripe.NewClient(os.Getenv("STRIPE_SECRET_KEY"))
	paymentIntent, err := sc.V1PaymentIntents.Retrieve(ctx, paymentIntentID, nil)
	if err != nil {
		return false, err
	}
	return paymentIntent.Status == stripe.PaymentIntentStatusSucceeded, nil
}

// orderProductsSubTotal matches OrderResolver.subTotal's reduce.
func orderProductsSubTotal(orderedProducts []models.OrderProduct) int {
	total := 0
	for _, op := range orderedProducts {
		total += op.Price * op.Count
	}
	return total
}

// primaryImageURL picks a product's primary image, falling back to the
// first one, matching `images.find(i => i.primary) ?? images[0]`.
func (r *Resolver) primaryImageURL(productID string) (string, error) {
	var images []models.ProductImage
	if err := r.DB.Where("product_id = ?", productID).Order("created_at asc").Find(&images).Error; err != nil {
		return "", err
	}
	if len(images) == 0 {
		return "", nil
	}
	for _, img := range images {
		if img.Primary {
			return img.URL, nil
		}
	}
	return images[0].URL, nil
}

// buildOrderEmailProductList matches the `productList` mapping shared by
// the admin-new-order/customer-new-order/order-has-shipped email variables
// in server/src/resolvers/order.ts.
func (r *Resolver) buildOrderEmailProductList(orderedProducts []models.OrderProduct) ([]map[string]string, error) {
	list := make([]map[string]string, 0, len(orderedProducts))
	for _, op := range orderedProducts {
		imageURL, err := r.primaryImageURL(op.ProductID)
		if err != nil {
			return nil, err
		}

		var product models.Product
		if err := r.DB.Where("id = ?", op.ProductID).First(&product).Error; err != nil {
			return nil, err
		}

		list = append(list, map[string]string{
			"imageUrl": imageURL,
			"id":       op.ProductID,
			"title":    product.Title,
			"cost":     fmt.Sprintf("$%.2f", float64(op.Price)/100),
			"quantity": strconv.Itoa(op.Count),
		})
	}
	return list, nil
}
