package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"errors"
	"fmt"
	"math"
	"os"
	"storeapi/internal/emails"
	"storeapi/internal/logger"
	"storeapi/internal/models"
	"strings"
	"time"

	stripe "github.com/stripe/stripe-go/v84"
)

// PlaceOrder is the resolver for the placeOrder field. Matches OrderResolver.placeOrder in server/src/resolvers/order.ts.
func (r *mutationResolver) PlaceOrder(ctx context.Context, addressID string, clientSecret string, notes *string, dryRun *bool, localDelivery *bool) (*models.Order, error) {
	user, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	isDryRun := boolOr(dryRun, false)
	isLocalDelivery := boolOr(localDelivery, false)
	notesValue := ""
	if notes != nil {
		notesValue = *notes
	}

	tx := r.DB.Begin()
	if tx.Error != nil {
		return nil, tx.Error
	}
	committed := false
	defer func() {
		if !committed {
			tx.Rollback()
		}
	}()

	if !isDryRun {
		succeeded, err := r.checkPaymentSucceeded(ctx, clientSecret)
		if err != nil {
			return nil, err
		}
		if !succeeded {
			return nil, errors.New("The payment for this order did not succeed.")
		}
	}

	paymentIntentID := strings.Split(clientSecret, "_secret")[0]

	shippingCost := models.CurrentShippingCost
	if isLocalDelivery {
		shippingCost = 0
	}

	order := &models.Order{
		AddressID:       addressID,
		UserID:          user.ID,
		PaymentIntentID: paymentIntentID,
		Notes:           notesValue,
		TaxRate:         models.CurrentTaxRate,
		ShippingCost:    shippingCost,
	}
	if err := tx.Create(order).Error; err != nil {
		return nil, err
	}

	var cart []models.UserProduct
	if err := tx.Where("user_id = ?", user.ID).Preload("Product").Find(&cart).Error; err != nil {
		return nil, err
	}

	orderedProducts := make([]models.OrderProduct, 0, len(cart))
	for _, item := range cart {
		product := item.Product

		op := models.OrderProduct{
			OrderID:   order.ID,
			ProductID: product.ID,
			Count:     item.Count,
			Price:     product.Price,
		}
		if err := tx.Create(&op).Error; err != nil {
			return nil, err
		}

		newQuantity := product.Quantity - op.Count
		if newQuantity < 0 {
			newQuantity = 0
		}
		product.Quantity = newQuantity
		if err := tx.Save(product).Error; err != nil {
			return nil, err
		}

		orderedProducts = append(orderedProducts, op)
	}
	order.OrderedProducts = orderedProducts

	if isDryRun {
		// Matches the Node resolver: a dry run returns the in-memory order (priced as if it were placed) without ever committing it.
		return order, nil
	}

	if err := tx.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	var address models.Address
	if err := r.DB.Where("id = ?", order.AddressID).First(&address).Error; err != nil {
		return nil, err
	}

	productList, err := r.buildOrderEmailProductList(orderedProducts)
	if err != nil {
		return nil, err
	}

	subTotal := orderProductsSubTotal(orderedProducts)
	tax := int(math.Floor(float64(subTotal) * order.TaxRate))
	totalCost := subTotal + order.ShippingCost + tax
	localDeliveryStr := "no"
	if isLocalDelivery {
		localDeliveryStr = "yes"
	}

	variables := emails.Variables{
		"email":            user.Email,
		"orderId":          order.ID,
		"stripePaymentUrl": fmt.Sprintf("https://dashboard.stripe.com/payments/%s", order.PaymentIntentID),
		"address":          address.String(),
		"notes":            notesValue,
		"productList":      productList,
		"subTotal":         fmt.Sprintf("%.2f", float64(subTotal)/100),
		"shippingCost":     fmt.Sprintf("%.2f", float64(order.ShippingCost)/100),
		"localDelivery":    localDeliveryStr,
		"tax":              fmt.Sprintf("%.2f", float64(tax)/100),
		"totalCost":        fmt.Sprintf("%.2f", float64(totalCost)/100),
	}

	// Matches the Node resolver: these are awaited inline with no error handling of their own, so a failed send surfaces as a placeOrder error even though the order above is already committed.
	if _, err := emails.Send(emails.AdminNewOrder, variables, ""); err != nil {
		return nil, err
	}
	if _, err := emails.Send(emails.CustomerNewOrder, variables, user.Email); err != nil {
		return nil, err
	}

	return order, nil
}

// UpdateOrder is the resolver for the updateOrder field.
func (r *mutationResolver) UpdateOrder(ctx context.Context, id string, shippedOn *time.Time, completedOn *time.Time, trackingNumber *string, notes *string) (*models.Order, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return nil, err
	}

	var order models.Order
	if err := r.DB.Where("id = ?", id).First(&order).Error; err != nil {
		return nil, errors.New("Invalid id")
	}

	shouldSendShippedEmail := (order.ShippedOn == nil || order.TrackingNumber == "") &&
		trackingNumber != nil && shippedOn != nil

	if shippedOn != nil {
		order.ShippedOn = shippedOn
	}
	if completedOn != nil {
		order.CompletedOn = completedOn
	}
	if trackingNumber != nil {
		order.TrackingNumber = *trackingNumber
	}
	if notes != nil {
		order.Notes = *notes
	}

	if err := r.DB.Save(&order).Error; err != nil {
		return nil, err
	}

	if shouldSendShippedEmail {
		var orderedProducts []models.OrderProduct
		if err := r.DB.Where("order_id = ?", order.ID).Find(&orderedProducts).Error; err != nil {
			return nil, err
		}
		order.OrderedProducts = orderedProducts

		var address models.Address
		if err := r.DB.Where("id = ?", order.AddressID).First(&address).Error; err != nil {
			return nil, err
		}
		var orderUser models.User
		if err := r.DB.Where("id = ?", order.UserID).First(&orderUser).Error; err != nil {
			return nil, err
		}

		productList, err := r.buildOrderEmailProductList(orderedProducts)
		if err != nil {
			return nil, err
		}

		subTotal := orderProductsSubTotal(orderedProducts)
		tax := int(math.Floor(float64(subTotal) * order.TaxRate))
		totalCost := subTotal + order.ShippingCost + tax

		variables := emails.Variables{
			// The Node resolver massages shippedOn by its own timezone offset before formatting; this just formats the date as given.
			"shippedDate":    shippedOn.Format("1/2/2006"),
			"trackingNumber": *trackingNumber,
			"orderId":        order.ID,
			"address":        address.String(),
			"notes":          order.Notes,
			"productList":    productList,
			"subTotal":       fmt.Sprintf("%.2f", float64(subTotal)/100),
			"shippingCost":   fmt.Sprintf("%.2f", float64(order.ShippingCost)/100),
			"tax":            fmt.Sprintf("%.2f", float64(tax)/100),
			"totalCost":      fmt.Sprintf("%.2f", float64(totalCost)/100),
		}

		if _, err := emails.Send(emails.OrderHasShipped, variables, orderUser.Email); err != nil {
			logger.Error("Error sending order-shipped email", "error", err)
		}
	}

	return &order, nil
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, email string, message string) (bool, error) {
	_, err := emails.Send(emails.ContactMessage, emails.Variables{"email": email, "message": message}, "")
	return err == nil, nil
}

// ShippingCost is the resolver for the shippingCost field. Float on the wire; the Go model keeps a plain int (cents).
func (r *orderResolver) ShippingCost(ctx context.Context, obj *models.Order) (float64, error) {
	return float64(obj.ShippingCost), nil
}

// User is the resolver for the user field.
func (r *orderResolver) User(ctx context.Context, obj *models.Order) (*models.User, error) {
	var user models.User
	if err := r.DB.Where("id = ?", obj.UserID).First(&user).Error; err != nil {
		return nil, errors.New("Order needs a user.")
	}
	return &user, nil
}

// Address is the resolver for the address field.
func (r *orderResolver) Address(ctx context.Context, obj *models.Order) (*models.Address, error) {
	return loaders(ctx).Address.Load(ctx, obj.AddressID)
}

// OrderedProducts is the resolver for the orderedProducts field. Always loader-based, matching the Node FieldResolver exactly (unlike SubTotal below, it does not short-circuit on obj.OrderedProducts), so a dry-run placeOrder's response, never persisted, legitimately comes back empty here even though its subTotal/totalCost are still correct.
func (r *orderResolver) OrderedProducts(ctx context.Context, obj *models.Order) ([]*models.OrderProduct, error) {
	l := loaders(ctx)

	ids, err := l.OrderProductIDsByOrder.Load(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	orderedProducts, err := l.OrderProduct.LoadAll(ctx, ids)
	if err != nil {
		return nil, err
	}

	out := make([]*models.OrderProduct, 0, len(orderedProducts))
	for _, op := range orderedProducts {
		if op != nil {
			out = append(out, op)
		}
	}
	return out, nil
}

// IsShipped is the resolver for the isShipped field.
func (r *orderResolver) IsShipped(ctx context.Context, obj *models.Order) (bool, error) {
	return obj.ShippedOn != nil, nil
}

// IsComplete is the resolver for the isComplete field.
func (r *orderResolver) IsComplete(ctx context.Context, obj *models.Order) (bool, error) {
	return obj.CompletedOn != nil, nil
}

// SubTotal is the resolver for the subTotal field.
func (r *orderResolver) SubTotal(ctx context.Context, obj *models.Order) (float64, error) {
	if len(obj.OrderedProducts) == 0 {
		var loaded []models.OrderProduct
		if err := r.DB.Where("order_id = ?", obj.ID).Find(&loaded).Error; err != nil {
			return 0, err
		}
		obj.OrderedProducts = loaded
	}
	return float64(orderProductsSubTotal(obj.OrderedProducts)), nil
}

// TotalCost is the resolver for the totalCost field.
func (r *orderResolver) TotalCost(ctx context.Context, obj *models.Order) (float64, error) {
	subTotal, err := r.SubTotal(ctx, obj)
	if err != nil {
		return 0, err
	}
	tax := math.Floor(subTotal * obj.TaxRate)
	return subTotal + float64(obj.ShippingCost) + tax, nil
}

// Count is the resolver for the count field. Float on the wire; the Go model keeps a plain int.
func (r *orderProductResolver) Count(ctx context.Context, obj *models.OrderProduct) (float64, error) {
	return float64(obj.Count), nil
}

// Price is the resolver for the price field.
func (r *orderProductResolver) Price(ctx context.Context, obj *models.OrderProduct) (float64, error) {
	return float64(obj.Price), nil
}

// Product is the resolver for the product field.
func (r *orderProductResolver) Product(ctx context.Context, obj *models.OrderProduct) (*models.Product, error) {
	product, err := loaders(ctx).Product.Load(ctx, obj.ProductID)
	if err != nil {
		return nil, err
	}
	if product == nil {
		return nil, errors.New("Ordered product needs a product associated.")
	}
	return product, nil
}

// AllOrders is the resolver for the allOrders field.
func (r *queryResolver) AllOrders(ctx context.Context, page *float64, perPage *float64, isShipped *bool, isComplete *bool) (*OrderPage, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return nil, err
	}

	pageNum := int(floatOr(page, 0))
	perPageNum := int(floatOr(perPage, 30))

	query := r.DB.Model(&models.Order{})
	if isShipped != nil {
		if *isShipped {
			query = query.Where("shipped_on IS NOT NULL")
		} else {
			query = query.Where("shipped_on IS NULL")
		}
	}
	if isComplete != nil {
		if *isComplete {
			query = query.Where("completed_on IS NOT NULL")
		} else {
			query = query.Where("completed_on IS NULL")
		}
	}

	var found []*models.Order
	err := query.Order("created_at DESC").
		Limit(perPageNum + 1).
		Offset(pageNum * perPageNum).
		Find(&found).Error
	if err != nil {
		return nil, err
	}

	hasMore := len(found) > perPageNum
	orders := found
	if hasMore {
		orders = found[:perPageNum]
	}

	result := &OrderPage{Edges: orders, HasMore: hasMore}
	if hasMore {
		next := float64(pageNum + 1)
		result.NextPage = &next
	}
	return result, nil
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context) ([]*models.Order, error) {
	user, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	var orders []*models.Order
	if err := r.DB.Where("user_id = ?", user.ID).Order("created_at DESC").Find(&orders).Error; err != nil {
		return nil, err
	}
	return orders, nil
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*models.Order, error) {
	user, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	query := r.DB.Where("id = ?", id)
	if !user.IsAdmin {
		query = query.Where("user_id = ?", user.ID)
	}

	var order models.Order
	if err := query.First(&order).Error; err != nil {
		return nil, nil
	}
	return &order, nil
}

// ClientSecret is the resolver for the clientSecret field.
func (r *queryResolver) ClientSecret(ctx context.Context, totalCost float64, clientSecret *string) (*string, error) {
	user, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	var cart []models.UserProduct
	if err := r.DB.Where("user_id = ?", user.ID).Preload("Product").Find(&cart).Error; err != nil {
		return nil, err
	}

	var description strings.Builder
	subTotal := 0
	for _, item := range cart {
		fmt.Fprintf(&description, "%s - $%.2f x%d \n", item.Product.Title, float64(item.Product.Price)/100, item.Count)
		subTotal += item.Product.Price * item.Count
	}
	fmt.Fprintf(&description, "Shipping - $%.2f \n", float64(models.CurrentShippingCost)/100)
	tax := math.Floor(models.CurrentTaxRate * float64(subTotal))
	fmt.Fprintf(&description, "Tax - $%.2f \n", tax/100)

	sc := stripe.NewClient(os.Getenv("STRIPE_SECRET_KEY"))

	var paymentIntent *stripe.PaymentIntent
	if clientSecret != nil && *clientSecret != "" {
		paymentIntentID := strings.Split(*clientSecret, "_secret")[0]
		paymentIntent, err = sc.V1PaymentIntents.Retrieve(ctx, paymentIntentID, nil)
		if err != nil {
			return nil, err
		}
		if paymentIntent.Status != stripe.PaymentIntentStatusSucceeded {
			paymentIntent, err = sc.V1PaymentIntents.Update(ctx, paymentIntentID, &stripe.PaymentIntentUpdateParams{
				Amount:      stripe.Int64(int64(totalCost)),
				Description: stripe.String(description.String()),
			})
			if err != nil {
				return nil, err
			}
		}
	} else {
		paymentIntent, err = sc.V1PaymentIntents.Create(ctx, &stripe.PaymentIntentCreateParams{
			Amount:      stripe.Int64(int64(totalCost)),
			Description: stripe.String(description.String()),
			Currency:    stripe.String("usd"),
			AutomaticPaymentMethods: &stripe.PaymentIntentCreateAutomaticPaymentMethodsParams{
				Enabled: stripe.Bool(true),
			},
		})
		if err != nil {
			return nil, err
		}
	}

	result := paymentIntent.ClientSecret
	return &result, nil
}

// PaymentSucceeded is the resolver for the paymentSucceeded field.
func (r *queryResolver) PaymentSucceeded(ctx context.Context, clientSecret string) (bool, error) {
	if _, err := requireUser(ctx); err != nil {
		return false, err
	}
	return r.checkPaymentSucceeded(ctx, clientSecret)
}

// Order returns OrderResolver implementation.
func (r *Resolver) Order() OrderResolver { return &orderResolver{r} }

// OrderProduct returns OrderProductResolver implementation.
func (r *Resolver) OrderProduct() OrderProductResolver { return &orderProductResolver{r} }

type orderResolver struct{ *Resolver }
type orderProductResolver struct{ *Resolver }
