package graph

// This file is NOT regenerated by gqlgen (no schema field matches this
// signature) — kept separate so `gqlgen generate` doesn't keep shuffling it
// to the bottom of product.resolvers.go.

import (
	"context"
	"strings"

	"storeapi/internal/models"
)

// findProducts backs both the products query and relatedProducts, mirroring
// ProductResolver.products in server/src/resolvers/product.ts. It returns
// up to perPage products (hasMore reports whether there were more).
func (r *Resolver) findProducts(ctx context.Context, page, perPage int, active *bool, search *string, tagSearch bool) ([]*models.Product, bool, error) {
	user := currentUser(ctx)

	query := r.DB.Model(&models.Product{})

	if user != nil && user.IsAdmin {
		if active != nil {
			query = query.Where("is_active = ?", *active)
		}
	} else {
		query = query.Where("is_active = ? AND (is_made_to_order = ? OR quantity > 0)", true, true)
	}

	if search != nil && strings.TrimSpace(*search) != "" {
		var searchItems []string
		if tagSearch {
			searchItems = []string{*search}
		} else {
			searchItems = strings.Fields(*search)
		}

		catWhere := make([]string, len(searchItems))
		catArgs := make([]any, len(searchItems))
		for i, item := range searchItems {
			catWhere[i] = "categories.name ILIKE ?"
			catArgs[i] = "%" + item + "%"
		}

		var categoryProductIDs []string
		err := r.DB.Table("product_categories").
			Distinct("product_categories.product_id").
			Joins("JOIN categories ON categories.id = product_categories.category_id").
			Where(strings.Join(catWhere, " OR "), catArgs...).
			Pluck("product_categories.product_id", &categoryProductIDs).Error
		if err != nil {
			return nil, false, err
		}

		orClause := "products.id IN ?"
		orArgs := []any{categoryProductIDs}
		if !tagSearch {
			for _, item := range searchItems {
				orClause += " OR products.title ILIKE ? OR products.description ILIKE ?"
				orArgs = append(orArgs, "%"+item+"%", "%"+item+"%")
			}
		}

		query = query.Where(orClause, orArgs...)
	}

	featureCountExpr := `(SELECT COUNT(*) FROM product_categories
		JOIN categories ON categories.id = product_categories.category_id
		WHERE categories.name = 'Feature'
		AND products.id = product_categories.product_id)`
	viewCountExpr := `(SELECT COUNT(*) FROM analytics
		WHERE analytics.modal = 'detail'
		AND analytics.modal_id = products.id)`

	var found []*models.Product
	err := query.
		Order(featureCountExpr + " DESC").
		Order(viewCountExpr + " DESC").
		Order("created_at DESC").
		Limit(perPage + 1).
		Offset(page * perPage).
		Find(&found).Error
	if err != nil {
		return nil, false, err
	}

	hasMore := len(found) > perPage
	if hasMore {
		found = found[:perPage]
	}
	return found, hasMore, nil
}
