package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"errors"
	"math/rand"
	"storeapi/internal/models"
	"strings"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, title string, description string, price float64, quantity float64, isMadeToOrder bool, isActive bool) (*models.Product, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return nil, err
	}

	product := &models.Product{
		Title:         title,
		Description:   description,
		Price:         int(price),
		Quantity:      int(quantity),
		IsMadeToOrder: isMadeToOrder,
		IsActive:      isActive,
	}
	if err := r.DB.Create(product).Error; err != nil {
		return nil, err
	}
	return product, nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, title *string, description *string, price *float64, quantity *float64, isMadeToOrder *bool, isActive *bool) (*models.Product, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return nil, err
	}

	var product models.Product
	if err := r.DB.Where("id = ?", id).First(&product).Error; err != nil {
		return nil, errors.New("Invalid id")
	}

	if title != nil {
		product.Title = *title
	}
	if description != nil {
		product.Description = *description
	}
	if price != nil {
		product.Price = int(*price)
	}
	if quantity != nil {
		product.Quantity = int(*quantity)
	}
	if isMadeToOrder != nil {
		product.IsMadeToOrder = *isMadeToOrder
	}
	if isActive != nil {
		product.IsActive = *isActive
	}

	if err := r.DB.Save(&product).Error; err != nil {
		return nil, err
	}
	return &product, nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (bool, error) {
	if _, err := requireAdmin(ctx); err != nil {
		return false, err
	}

	result := r.DB.Where("id = ?", id).Delete(&models.Product{})
	if result.Error != nil {
		return false, result.Error
	}
	return result.RowsAffected > 0, nil
}

// Price is the resolver for the price field. Float on the wire (see schema/product.graphqls); the Go model keeps a plain int.
func (r *productResolver) Price(ctx context.Context, obj *models.Product) (float64, error) {
	return float64(obj.Price), nil
}

// Quantity is the resolver for the quantity field.
func (r *productResolver) Quantity(ctx context.Context, obj *models.Product) (float64, error) {
	return float64(obj.Quantity), nil
}

// Categories is the resolver for the categories field.
func (r *productResolver) Categories(ctx context.Context, obj *models.Product) ([]*models.Category, error) {
	l := loaders(ctx)

	categoryIDs, err := l.CategoryIDsByProduct.Load(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	categories, err := l.Category.LoadAll(ctx, categoryIDs)
	if err != nil {
		return nil, err
	}

	out := make([]*models.Category, 0, len(categories))
	for _, c := range categories {
		if c != nil {
			out = append(out, c)
		}
	}
	return out, nil
}

// Images is the resolver for the images field.
func (r *productResolver) Images(ctx context.Context, obj *models.Product) ([]*models.ProductImage, error) {
	l := loaders(ctx)

	imageIDs, err := l.ImageIDsByProduct.Load(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	images, err := l.Image.LoadAll(ctx, imageIDs)
	if err != nil {
		return nil, err
	}

	out := make([]*models.ProductImage, 0, len(images))
	for _, i := range images {
		if i != nil {
			out = append(out, i)
		}
	}
	return out, nil
}

// RelatedProducts is the resolver for the relatedProducts field. Matches ProductResolver.relatedProducts: search active products by this product's category names, shuffle, and keep up to 7 excluding itself.
func (r *productResolver) RelatedProducts(ctx context.Context, obj *models.Product) ([]*models.Product, error) {
	categories, err := r.Categories(ctx, obj)
	if err != nil {
		return nil, err
	}
	names := make([]string, len(categories))
	for i, c := range categories {
		names[i] = c.Name
	}
	search := strings.Join(names, " ")

	active := true
	found, _, err := r.findProducts(ctx, 0, 20, &active, &search, true)
	if err != nil {
		return nil, err
	}

	rand.Shuffle(len(found), func(i, j int) { found[i], found[j] = found[j], found[i] })

	related := make([]*models.Product, 0, 7)
	for _, p := range found {
		if len(related) >= 7 {
			break
		}
		if p.ID != obj.ID {
			related = append(related, p)
		}
	}
	return related, nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, page *float64, perPage *float64, active *bool, search *string, tagSearch *bool) (*ProductPage, error) {
	pageNum := int(floatOr(page, 0))
	perPageNum := int(floatOr(perPage, 20))
	isTagSearch := boolOr(tagSearch, false)

	found, hasMore, err := r.findProducts(ctx, pageNum, perPageNum, active, search, isTagSearch)
	if err != nil {
		return nil, err
	}

	result := &ProductPage{Edges: found, HasMore: hasMore}
	if hasMore {
		next := float64(pageNum + 1)
		result.NextPage = &next
	}
	return result, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string, active *bool) (*models.Product, error) {
	user := currentUser(ctx)

	query := r.DB.Where("id = ?", id)
	if user != nil && user.IsAdmin {
		if active != nil {
			query = query.Where("is_active = ?", *active)
		}
	} else {
		query = query.Where("is_active = ?", true)
	}

	var product models.Product
	if err := query.First(&product).Error; err != nil {
		return nil, errors.New("Invalid id")
	}
	return &product, nil
}

// Product returns ProductResolver implementation.
func (r *Resolver) Product() ProductResolver { return &productResolver{r} }

type productResolver struct{ *Resolver }
