package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"errors"
	"fmt"
	"os"
	"storeapi/internal/emails"
	"storeapi/internal/models"
	"strings"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string) (*models.User, error) {
	user := &models.User{Email: email}
	if err := user.SetPassword(password); err != nil {
		return nil, err
	}

	tx := r.DB.Begin()
	if tx.Error != nil {
		return nil, tx.Error
	}

	if err := tx.Create(user).Error; err != nil {
		tx.Rollback()
		return nil, err
	}

	token, err := models.GenerateToken(tx, user.ID, tokenDaysValid)
	if err != nil {
		tx.Rollback()
		return nil, err
	}

	if err := tx.Commit().Error; err != nil {
		return nil, err
	}

	user.Tokens = []models.Token{*token}
	setToken(ctx, token.Value)

	return user, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*models.User, error) {
	tx := r.DB.Begin()
	if tx.Error != nil {
		return nil, tx.Error
	}

	var user models.User
	if err := tx.Where("email ILIKE ?", email).First(&user).Error; err != nil {
		tx.Rollback()
		return nil, errors.New("Invalid email or password")
	}

	if err := user.ComparePassword(password); err != nil {
		tx.Rollback()
		return nil, errors.New("Invalid email or password")
	}

	token, err := models.GenerateToken(tx, user.ID, tokenDaysValid)
	if err != nil {
		tx.Rollback()
		return nil, err
	}

	if err := tx.Commit().Error; err != nil {
		return nil, err
	}

	user.Tokens = []models.Token{*token}
	setToken(ctx, token.Value)

	return &user, nil
}

// ChangeEmail is the resolver for the changeEmail field.
func (r *mutationResolver) ChangeEmail(ctx context.Context, email string) (*models.User, error) {
	user, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	user.Email = email
	if err := r.DB.Save(user).Error; err != nil {
		return nil, err
	}

	return user, nil
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, old string, new string) (bool, error) {
	user, err := requireUser(ctx)
	if err != nil {
		return false, err
	}

	if err := user.ComparePassword(old); err != nil {
		return false, errors.New("Invalid old password")
	}

	if err := user.SetPassword(new); err != nil {
		return false, err
	}
	if err := r.DB.Save(user).Error; err != nil {
		return false, err
	}

	return true, nil
}

// ForgotPassword is the resolver for the forgotPassword field.
func (r *mutationResolver) ForgotPassword(ctx context.Context, email string) (bool, error) {
	var user models.User
	if err := r.DB.Where("email ILIKE ?", email).First(&user).Error; err != nil {
		// Same as the Node resolver: don't reveal whether the address exists.
		return true, nil
	}

	token, err := models.GenerateToken(r.DB, user.ID, resetTokenDaysValid)
	if err != nil {
		return false, err
	}

	link := fmt.Sprintf(
		"%s/?modal=reset-forgotten-password&modal-params=token&token=%s",
		os.Getenv("APP_BASE_URL"), token.Value,
	)
	variables := emails.Variables{
		"email": email,
		"actionButton": []map[string]string{
			{"actionText": "Reset my password", "actionLink": link},
		},
	}

	_, err = emails.Send(emails.ForgotPassword, variables, user.Email)
	return err == nil, nil
}

// ResetForgottenPassword is the resolver for the resetForgottenPassword field.
func (r *mutationResolver) ResetForgottenPassword(ctx context.Context, email string, password string, token string) (bool, error) {
	user, err := models.VerifyAndFindUser(r.DB, token)
	if err != nil {
		return false, err
	}
	if user == nil {
		return false, errors.New("There is a problem with this link. Please try getting another link.")
	}

	if !strings.EqualFold(user.Email, email) {
		return false, errors.New("This email does not match any in our system. Please try again.")
	}

	if err := user.SetPassword(password); err != nil {
		return false, err
	}
	if err := r.DB.Save(user).Error; err != nil {
		return false, err
	}

	return true, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	if _, err := requireUser(ctx); err != nil {
		return false, err
	}

	value := models.UnsignTokenValue(tokenFromContext(ctx))
	result := r.DB.Where("value = ?", value).Delete(&models.Token{})
	if result.Error != nil {
		return false, result.Error
	}

	removeToken(ctx)
	return result.RowsAffected > 0, nil
}

// LogoutEverywhere is the resolver for the logoutEverywhere field.
func (r *mutationResolver) LogoutEverywhere(ctx context.Context) (*models.Token, error) {
	user, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	tx := r.DB.Begin()
	if tx.Error != nil {
		return nil, tx.Error
	}

	if err := tx.Where("user_id = ?", user.ID).Delete(&models.Token{}).Error; err != nil {
		tx.Rollback()
		return nil, err
	}

	token, err := models.GenerateToken(tx, user.ID, tokenDaysValid)
	if err != nil {
		tx.Rollback()
		return nil, err
	}

	if err := tx.Commit().Error; err != nil {
		return nil, err
	}

	setToken(ctx, token.Value)
	return token, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	return currentUser(ctx), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
