package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"sort"
	"storeapi/internal/models"
)

// Tokens is the resolver for the tokens field. Matches the FieldResolver in server/src/resolvers/user.ts: returns the already-loaded tokens (set by register/login on the object we just handed back) if present, otherwise looks them up by userId. Not loader-based on the Node side either.
func (r *userResolver) Tokens(ctx context.Context, obj *models.User) ([]*models.Token, error) {
	if len(obj.Tokens) > 0 {
		tokens := make([]*models.Token, len(obj.Tokens))
		for i := range obj.Tokens {
			tokens[i] = &obj.Tokens[i]
		}
		return tokens, nil
	}

	var tokens []*models.Token
	if err := r.DB.Where("user_id = ?", obj.ID).Find(&tokens).Error; err != nil {
		return nil, err
	}
	return tokens, nil
}

// Addresses is the resolver for the addresses field.
func (r *userResolver) Addresses(ctx context.Context, obj *models.User) ([]*models.Address, error) {
	return r.loadAddresses(ctx, obj.ID)
}

// BillingAddress is the resolver for the billingAddress field.
func (r *userResolver) BillingAddress(ctx context.Context, obj *models.User) (*models.Address, error) {
	addresses, err := r.loadAddresses(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	for _, a := range addresses {
		if a.Type == models.AddressTypeBilling {
			return a, nil
		}
	}
	return nil, nil
}

// ShippingAddresses is the resolver for the shippingAddresses field.
func (r *userResolver) ShippingAddresses(ctx context.Context, obj *models.User) ([]*models.Address, error) {
	addresses, err := r.loadAddresses(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	out := make([]*models.Address, 0, len(addresses))
	for _, a := range addresses {
		if a.Type == models.AddressTypeShipping {
			out = append(out, a)
		}
	}
	return out, nil
}

// Orders is the resolver for the orders field.
func (r *userResolver) Orders(ctx context.Context, obj *models.User) ([]*models.Order, error) {
	l := loaders(ctx)

	orderIDs, err := l.OrderIDsByUser.Load(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	orders, err := l.Order.LoadAll(ctx, orderIDs)
	if err != nil {
		return nil, err
	}

	out := make([]*models.Order, 0, len(orders))
	for _, o := range orders {
		if o != nil {
			out = append(out, o)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].CreatedAt.After(out[j].CreatedAt) })
	return out, nil
}

// Cart is the resolver for the cart field.
func (r *userResolver) Cart(ctx context.Context, obj *models.User) ([]*models.UserProduct, error) {
	l := loaders(ctx)

	ids, err := l.UserProductIDsByUser.Load(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	cart, err := l.UserProduct.LoadAll(ctx, ids)
	if err != nil {
		return nil, err
	}

	out := make([]*models.UserProduct, 0, len(cart))
	for _, c := range cart {
		if c != nil {
			out = append(out, c)
		}
	}
	return out, nil
}

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *userResolver) loadAddresses(ctx context.Context, userID string) ([]*models.Address, error) {
	l := loaders(ctx)

	addressIDs, err := l.AddressIDsByUser.Load(ctx, userID)
	if err != nil {
		return nil, err
	}
	addresses, err := l.Address.LoadAll(ctx, addressIDs)
	if err != nil {
		return nil, err
	}

	out := make([]*models.Address, 0, len(addresses))
	for _, a := range addresses {
		if a != nil {
			out = append(out, a)
		}
	}
	return out, nil
}
